# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coupledAntennasAnalysisWindow_v0.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainAnalysisCoupledAntennasWindow(object):
    def setupUi(self, MainAnalysisCoupledAntennasWindow):
        MainAnalysisCoupledAntennasWindow.setObjectName("MainAnalysisCoupledAntennasWindow")
        MainAnalysisCoupledAntennasWindow.resize(1158, 705)
        self.centralwidget = QtWidgets.QWidget(MainAnalysisCoupledAntennasWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem = QtWidgets.QSpacerItem(13, 580, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.pushButtonPreviousFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPreviousFile.setMinimumSize(QtCore.QSize(50, 25))
        self.pushButtonPreviousFile.setMaximumSize(QtCore.QSize(50, 25))
        self.pushButtonPreviousFile.setObjectName("pushButtonPreviousFile")
        self.horizontalLayout_18.addWidget(self.pushButtonPreviousFile)
        spacerItem2 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem2)
        self.pushButtonNextFile = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonNextFile.setMinimumSize(QtCore.QSize(50, 25))
        self.pushButtonNextFile.setMaximumSize(QtCore.QSize(50, 25))
        self.pushButtonNextFile.setObjectName("pushButtonNextFile")
        self.horizontalLayout_18.addWidget(self.pushButtonNextFile)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_18)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        spacerItem4 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.MplWidget4 = MplWidget4p(self.centralwidget)
        self.MplWidget4.setMinimumSize(QtCore.QSize(550, 400))
        self.MplWidget4.setObjectName("MplWidget4")
        self.verticalLayout.addWidget(self.MplWidget4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setMinimumSize(QtCore.QSize(100, 70))
        self.groupBox_9.setObjectName("groupBox_9")
        self.lineEditValueFmin = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditValueFmin.setGeometry(QtCore.QRect(20, 30, 50, 25))
        self.lineEditValueFmin.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueFmin.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueFmin.setFont(font)
        self.lineEditValueFmin.setObjectName("lineEditValueFmin")
        self.horizontalLayout.addWidget(self.groupBox_9)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setMinimumSize(QtCore.QSize(100, 70))
        self.groupBox_8.setObjectName("groupBox_8")
        self.lineEditValueFmax = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEditValueFmax.setGeometry(QtCore.QRect(20, 30, 50, 25))
        self.lineEditValueFmax.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueFmax.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueFmax.setFont(font)
        self.lineEditValueFmax.setObjectName("lineEditValueFmax")
        self.horizontalLayout.addWidget(self.groupBox_8)
        self.horizontalLayout_8.addLayout(self.horizontalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEditF2Max = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditF2Max.setFont(font)
        self.lineEditF2Max.setObjectName("lineEditF2Max")
        self.gridLayout_5.addWidget(self.lineEditF2Max, 2, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 2, 3, 1, 1)
        self.lineEditF2Min = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditF2Min.setFont(font)
        self.lineEditF2Min.setObjectName("lineEditF2Min")
        self.gridLayout_5.addWidget(self.lineEditF2Min, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 1, 3, 1, 1)
        self.radioButton2RegionsFit = QtWidgets.QRadioButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButton2RegionsFit.setFont(font)
        self.radioButton2RegionsFit.setObjectName("radioButton2RegionsFit")
        self.gridLayout_5.addWidget(self.radioButton2RegionsFit, 0, 3, 1, 2)
        self.lineEditF1Min = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditF1Min.setFont(font)
        self.lineEditF1Min.setObjectName("lineEditF1Min")
        self.gridLayout_5.addWidget(self.lineEditF1Min, 1, 1, 1, 1)
        self.pushButtonFit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonFit.setObjectName("pushButtonFit")
        self.gridLayout_5.addWidget(self.pushButtonFit, 0, 1, 1, 1)
        self.lineEditF1Max = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditF1Max.setFont(font)
        self.lineEditF1Max.setObjectName("lineEditF1Max")
        self.gridLayout_5.addWidget(self.lineEditF1Max, 1, 4, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_5)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_20.addLayout(self.verticalLayout)
        spacerItem8 = QtWidgets.QSpacerItem(13, 580, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem8)
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem9 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(220, 120))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 23, 172, 92))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.horizontalSliderR0 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSliderR0.setMinimum(0)
        self.horizontalSliderR0.setMaximum(10000)
        self.horizontalSliderR0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderR0.setObjectName("horizontalSliderR0")
        self.verticalLayout_40.addWidget(self.horizontalSliderR0)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_39.addWidget(self.label_5)
        self.lineEditMinR0 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditMinR0.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinR0.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinR0.setFont(font)
        self.lineEditMinR0.setObjectName("lineEditMinR0")
        self.verticalLayout_39.addWidget(self.lineEditMinR0)
        self.horizontalLayout_2.addLayout(self.verticalLayout_39)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_38.addWidget(self.label_7)
        self.lineEditValueR0 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditValueR0.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueR0.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueR0.setFont(font)
        self.lineEditValueR0.setObjectName("lineEditValueR0")
        self.verticalLayout_38.addWidget(self.lineEditValueR0)
        self.horizontalLayout_2.addLayout(self.verticalLayout_38)
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_37.addWidget(self.label_6)
        self.lineEditMaxR0 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditMaxR0.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxR0.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxR0.setFont(font)
        self.lineEditMaxR0.setObjectName("lineEditMaxR0")
        self.verticalLayout_37.addWidget(self.lineEditMaxR0)
        self.horizontalLayout_2.addLayout(self.verticalLayout_37)
        self.verticalLayout_40.addLayout(self.horizontalLayout_2)
        self.radioButtonFitR0 = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitR0.setFont(font)
        self.radioButtonFitR0.setObjectName("radioButtonFitR0")
        self.verticalLayout_40.addWidget(self.radioButtonFitR0)
        self.horizontalLayout_11.addWidget(self.groupBox)
        spacerItem10 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem10)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(220, 120))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 23, 172, 92))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.horizontalSliderR1 = QtWidgets.QSlider(self.layoutWidget1)
        self.horizontalSliderR1.setMinimum(0)
        self.horizontalSliderR1.setMaximum(10000)
        self.horizontalSliderR1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderR1.setObjectName("horizontalSliderR1")
        self.verticalLayout_41.addWidget(self.horizontalSliderR1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_33 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_36.addWidget(self.label_33)
        self.lineEditMinR1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditMinR1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinR1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinR1.setFont(font)
        self.lineEditMinR1.setObjectName("lineEditMinR1")
        self.verticalLayout_36.addWidget(self.lineEditMinR1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_36)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_34 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_4.addWidget(self.label_34)
        self.lineEditValueR1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditValueR1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueR1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueR1.setFont(font)
        self.lineEditValueR1.setObjectName("lineEditValueR1")
        self.verticalLayout_4.addWidget(self.lineEditValueR1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_32 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_3.addWidget(self.label_32)
        self.lineEditMaxR1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditMaxR1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxR1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxR1.setFont(font)
        self.lineEditMaxR1.setObjectName("lineEditMaxR1")
        self.verticalLayout_3.addWidget(self.lineEditMaxR1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_41.addLayout(self.horizontalLayout_3)
        self.radioButtonFitR1 = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitR1.setFont(font)
        self.radioButtonFitR1.setObjectName("radioButtonFitR1")
        self.verticalLayout_41.addWidget(self.radioButtonFitR1)
        self.horizontalLayout_11.addWidget(self.groupBox_2)
        spacerItem11 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem11)
        self.verticalLayout_42.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem12 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem12)
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setMinimumSize(QtCore.QSize(220, 120))
        self.groupBox_11.setObjectName("groupBox_11")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_11)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 23, 172, 92))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.horizontalSliderL1 = QtWidgets.QSlider(self.layoutWidget2)
        self.horizontalSliderL1.setMinimum(0)
        self.horizontalSliderL1.setMaximum(10000)
        self.horizontalSliderL1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderL1.setObjectName("horizontalSliderL1")
        self.verticalLayout_35.addWidget(self.horizontalSliderL1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout()
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_30.addWidget(self.label_30)
        self.lineEditMinL1 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditMinL1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinL1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinL1.setFont(font)
        self.lineEditMinL1.setObjectName("lineEditMinL1")
        self.verticalLayout_30.addWidget(self.lineEditMinL1)
        self.horizontalLayout_15.addLayout(self.verticalLayout_30)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_31 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_6.addWidget(self.label_31)
        self.lineEditValueL1 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditValueL1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueL1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueL1.setFont(font)
        self.lineEditValueL1.setObjectName("lineEditValueL1")
        self.verticalLayout_6.addWidget(self.lineEditValueL1)
        self.horizontalLayout_15.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_29 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_5.addWidget(self.label_29)
        self.lineEditMaxL1 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditMaxL1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxL1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxL1.setFont(font)
        self.lineEditMaxL1.setObjectName("lineEditMaxL1")
        self.verticalLayout_5.addWidget(self.lineEditMaxL1)
        self.horizontalLayout_15.addLayout(self.verticalLayout_5)
        self.verticalLayout_35.addLayout(self.horizontalLayout_15)
        self.radioButtonFitL1 = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitL1.setFont(font)
        self.radioButtonFitL1.setObjectName("radioButtonFitL1")
        self.verticalLayout_35.addWidget(self.radioButtonFitL1)
        self.horizontalLayout_16.addWidget(self.groupBox_11)
        spacerItem13 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem13)
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_12.setMinimumSize(QtCore.QSize(220, 120))
        self.groupBox_12.setObjectName("groupBox_12")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_12)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 23, 172, 92))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.horizontalSliderC1 = QtWidgets.QSlider(self.layoutWidget3)
        self.horizontalSliderC1.setMinimum(0)
        self.horizontalSliderC1.setMaximum(10000)
        self.horizontalSliderC1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderC1.setObjectName("horizontalSliderC1")
        self.verticalLayout_34.addWidget(self.horizontalSliderC1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_27 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_31.addWidget(self.label_27)
        self.lineEditMinC1 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEditMinC1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinC1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinC1.setFont(font)
        self.lineEditMinC1.setObjectName("lineEditMinC1")
        self.verticalLayout_31.addWidget(self.lineEditMinC1)
        self.horizontalLayout_10.addLayout(self.verticalLayout_31)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout()
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_28 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_32.addWidget(self.label_28)
        self.lineEditValueC1 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEditValueC1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueC1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueC1.setFont(font)
        self.lineEditValueC1.setObjectName("lineEditValueC1")
        self.verticalLayout_32.addWidget(self.lineEditValueC1)
        self.horizontalLayout_10.addLayout(self.verticalLayout_32)
        self.verticalLayout_33 = QtWidgets.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_26 = QtWidgets.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_33.addWidget(self.label_26)
        self.lineEditMaxC1 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEditMaxC1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxC1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxC1.setFont(font)
        self.lineEditMaxC1.setObjectName("lineEditMaxC1")
        self.verticalLayout_33.addWidget(self.lineEditMaxC1)
        self.horizontalLayout_10.addLayout(self.verticalLayout_33)
        self.verticalLayout_34.addLayout(self.horizontalLayout_10)
        self.radioButtonFitC1 = QtWidgets.QRadioButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitC1.setFont(font)
        self.radioButtonFitC1.setObjectName("radioButtonFitC1")
        self.verticalLayout_34.addWidget(self.radioButtonFitC1)
        self.horizontalLayout_16.addWidget(self.groupBox_12)
        spacerItem14 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem14)
        self.verticalLayout_42.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem15 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem15)
        self.groupBox_13 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_13.setMinimumSize(QtCore.QSize(220, 120))
        self.groupBox_13.setObjectName("groupBox_13")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_13)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 23, 172, 92))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.horizontalSliderk = QtWidgets.QSlider(self.layoutWidget4)
        self.horizontalSliderk.setMinimum(0)
        self.horizontalSliderk.setMaximum(10000)
        self.horizontalSliderk.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderk.setObjectName("horizontalSliderk")
        self.verticalLayout_28.addWidget(self.horizontalSliderk)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_7.addWidget(self.label_21)
        self.lineEditMink = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEditMink.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMink.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMink.setFont(font)
        self.lineEditMink.setObjectName("lineEditMink")
        self.verticalLayout_7.addWidget(self.lineEditMink)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_22 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.label_22)
        self.lineEditValuek = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEditValuek.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValuek.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValuek.setFont(font)
        self.lineEditValuek.setObjectName("lineEditValuek")
        self.verticalLayout_8.addWidget(self.lineEditValuek)
        self.horizontalLayout_9.addLayout(self.verticalLayout_8)
        self.verticalLayout_24 = QtWidgets.QVBoxLayout()
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_20 = QtWidgets.QLabel(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_24.addWidget(self.label_20)
        self.lineEditMaxk = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEditMaxk.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxk.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxk.setFont(font)
        self.lineEditMaxk.setObjectName("lineEditMaxk")
        self.verticalLayout_24.addWidget(self.lineEditMaxk)
        self.horizontalLayout_9.addLayout(self.verticalLayout_24)
        self.verticalLayout_28.addLayout(self.horizontalLayout_9)
        self.radioButtonFitk = QtWidgets.QRadioButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitk.setFont(font)
        self.radioButtonFitk.setChecked(True)
        self.radioButtonFitk.setObjectName("radioButtonFitk")
        self.verticalLayout_28.addWidget(self.radioButtonFitk)
        self.horizontalLayout_17.addWidget(self.groupBox_13)
        spacerItem16 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem16)
        self.groupBox_15 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_15.setMinimumSize(QtCore.QSize(220, 120))
        self.groupBox_15.setObjectName("groupBox_15")
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_15)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 23, 172, 92))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.horizontalSliderR2 = QtWidgets.QSlider(self.layoutWidget5)
        self.horizontalSliderR2.setMinimum(0)
        self.horizontalSliderR2.setMaximum(10000)
        self.horizontalSliderR2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderR2.setObjectName("horizontalSliderR2")
        self.verticalLayout_29.addWidget(self.horizontalSliderR2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_25.addWidget(self.label_24)
        self.lineEditMinR2 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEditMinR2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinR2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinR2.setFont(font)
        self.lineEditMinR2.setObjectName("lineEditMinR2")
        self.verticalLayout_25.addWidget(self.lineEditMinR2)
        self.horizontalLayout_14.addLayout(self.verticalLayout_25)
        self.verticalLayout_26 = QtWidgets.QVBoxLayout()
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_25 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_26.addWidget(self.label_25)
        self.lineEditValueR2 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEditValueR2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueR2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueR2.setFont(font)
        self.lineEditValueR2.setObjectName("lineEditValueR2")
        self.verticalLayout_26.addWidget(self.lineEditValueR2)
        self.horizontalLayout_14.addLayout(self.verticalLayout_26)
        self.verticalLayout_27 = QtWidgets.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_23 = QtWidgets.QLabel(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_27.addWidget(self.label_23)
        self.lineEditMaxR2 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEditMaxR2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxR2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxR2.setFont(font)
        self.lineEditMaxR2.setObjectName("lineEditMaxR2")
        self.verticalLayout_27.addWidget(self.lineEditMaxR2)
        self.horizontalLayout_14.addLayout(self.verticalLayout_27)
        self.verticalLayout_29.addLayout(self.horizontalLayout_14)
        self.radioButtonFitR2 = QtWidgets.QRadioButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitR2.setFont(font)
        self.radioButtonFitR2.setObjectName("radioButtonFitR2")
        self.verticalLayout_29.addWidget(self.radioButtonFitR2)
        self.horizontalLayout_17.addWidget(self.groupBox_15)
        spacerItem17 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem17)
        self.verticalLayout_42.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem18 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem18)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(220, 120))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 23, 172, 92))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalSliderL2 = QtWidgets.QSlider(self.layoutWidget6)
        self.horizontalSliderL2.setMinimum(0)
        self.horizontalSliderL2.setMaximum(10000)
        self.horizontalSliderL2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderL2.setObjectName("horizontalSliderL2")
        self.verticalLayout_20.addWidget(self.horizontalSliderL2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_19.addWidget(self.label_15)
        self.lineEditMinL2 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEditMinL2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinL2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinL2.setFont(font)
        self.lineEditMinL2.setObjectName("lineEditMinL2")
        self.verticalLayout_19.addWidget(self.lineEditMinL2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_19)
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_18.addWidget(self.label_16)
        self.lineEditValueL2 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEditValueL2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueL2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueL2.setFont(font)
        self.lineEditValueL2.setObjectName("lineEditValueL2")
        self.verticalLayout_18.addWidget(self.lineEditValueL2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_18)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_9.addWidget(self.label_14)
        self.lineEditMaxL2 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEditMaxL2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxL2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxL2.setFont(font)
        self.lineEditMaxL2.setObjectName("lineEditMaxL2")
        self.verticalLayout_9.addWidget(self.lineEditMaxL2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        self.verticalLayout_20.addLayout(self.horizontalLayout_5)
        self.radioButtonFitL2 = QtWidgets.QRadioButton(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitL2.setFont(font)
        self.radioButtonFitL2.setObjectName("radioButtonFitL2")
        self.verticalLayout_20.addWidget(self.radioButtonFitL2)
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        spacerItem19 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem19)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(220, 120))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 23, 172, 92))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.horizontalSliderC2 = QtWidgets.QSlider(self.layoutWidget7)
        self.horizontalSliderC2.setMinimum(0)
        self.horizontalSliderC2.setMaximum(10000)
        self.horizontalSliderC2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderC2.setObjectName("horizontalSliderC2")
        self.verticalLayout_23.addWidget(self.horizontalSliderC2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_10.addWidget(self.label_18)
        self.lineEditMinC2 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEditMinC2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinC2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinC2.setFont(font)
        self.lineEditMinC2.setObjectName("lineEditMinC2")
        self.verticalLayout_10.addWidget(self.lineEditMinC2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_10)
        self.verticalLayout_21 = QtWidgets.QVBoxLayout()
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_21.addWidget(self.label_19)
        self.lineEditValueC2 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEditValueC2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueC2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueC2.setFont(font)
        self.lineEditValueC2.setObjectName("lineEditValueC2")
        self.verticalLayout_21.addWidget(self.lineEditValueC2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_21)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_22.addWidget(self.label_17)
        self.lineEditMaxC2 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEditMaxC2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxC2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxC2.setFont(font)
        self.lineEditMaxC2.setObjectName("lineEditMaxC2")
        self.verticalLayout_22.addWidget(self.lineEditMaxC2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_22)
        self.verticalLayout_23.addLayout(self.horizontalLayout_6)
        self.radioButtonFitC2 = QtWidgets.QRadioButton(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitC2.setFont(font)
        self.radioButtonFitC2.setObjectName("radioButtonFitC2")
        self.verticalLayout_23.addWidget(self.radioButtonFitC2)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        spacerItem20 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem20)
        self.verticalLayout_42.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem21 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem21)
        self.R_sensor = QtWidgets.QGroupBox(self.centralwidget)
        self.R_sensor.setMinimumSize(QtCore.QSize(220, 120))
        self.R_sensor.setObjectName("R_sensor")
        self.layoutWidget8 = QtWidgets.QWidget(self.R_sensor)
        self.layoutWidget8.setGeometry(QtCore.QRect(11, 24, 172, 92))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalSliderRsensor = QtWidgets.QSlider(self.layoutWidget8)
        self.horizontalSliderRsensor.setMinimum(0)
        self.horizontalSliderRsensor.setMaximum(10000)
        self.horizontalSliderRsensor.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderRsensor.setObjectName("horizontalSliderRsensor")
        self.verticalLayout_14.addWidget(self.horizontalSliderRsensor)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.lineEditMinRsensor = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEditMinRsensor.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinRsensor.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinRsensor.setFont(font)
        self.lineEditMinRsensor.setObjectName("lineEditMinRsensor")
        self.verticalLayout_2.addWidget(self.lineEditMinRsensor)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_11.addWidget(self.label_10)
        self.lineEditValueRsensor = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEditValueRsensor.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueRsensor.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueRsensor.setFont(font)
        self.lineEditValueRsensor.setObjectName("lineEditValueRsensor")
        self.verticalLayout_11.addWidget(self.lineEditValueRsensor)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_13.addWidget(self.label_8)
        self.lineEditMaxRsensor = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEditMaxRsensor.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxRsensor.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxRsensor.setFont(font)
        self.lineEditMaxRsensor.setObjectName("lineEditMaxRsensor")
        self.verticalLayout_13.addWidget(self.lineEditMaxRsensor)
        self.horizontalLayout_4.addLayout(self.verticalLayout_13)
        self.verticalLayout_14.addLayout(self.horizontalLayout_4)
        self.radioButtonFitRsensor = QtWidgets.QRadioButton(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitRsensor.setFont(font)
        self.radioButtonFitRsensor.setObjectName("radioButtonFitRsensor")
        self.verticalLayout_14.addWidget(self.radioButtonFitRsensor)
        self.horizontalLayout_13.addWidget(self.R_sensor)
        spacerItem22 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem22)
        self.groupBox_14 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_14.setMinimumSize(QtCore.QSize(220, 120))
        self.groupBox_14.setObjectName("groupBox_14")
        self.layoutWidget9 = QtWidgets.QWidget(self.groupBox_14)
        self.layoutWidget9.setGeometry(QtCore.QRect(10, 23, 172, 92))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalSliderCsensor = QtWidgets.QSlider(self.layoutWidget9)
        self.horizontalSliderCsensor.setMinimum(0)
        self.horizontalSliderCsensor.setMaximum(10000)
        self.horizontalSliderCsensor.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCsensor.setObjectName("horizontalSliderCsensor")
        self.verticalLayout_17.addWidget(self.horizontalSliderCsensor)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_12.addWidget(self.label_12)
        self.lineEditMinCsensor = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEditMinCsensor.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinCsensor.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinCsensor.setFont(font)
        self.lineEditMinCsensor.setObjectName("lineEditMinCsensor")
        self.verticalLayout_12.addWidget(self.lineEditMinCsensor)
        self.horizontalLayout_12.addLayout(self.verticalLayout_12)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_15.addWidget(self.label_13)
        self.lineEditValueCsensor = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEditValueCsensor.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueCsensor.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueCsensor.setFont(font)
        self.lineEditValueCsensor.setObjectName("lineEditValueCsensor")
        self.verticalLayout_15.addWidget(self.lineEditValueCsensor)
        self.horizontalLayout_12.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_16.addWidget(self.label_11)
        self.lineEditMaxCsensor = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEditMaxCsensor.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxCsensor.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxCsensor.setFont(font)
        self.lineEditMaxCsensor.setObjectName("lineEditMaxCsensor")
        self.verticalLayout_16.addWidget(self.lineEditMaxCsensor)
        self.horizontalLayout_12.addLayout(self.verticalLayout_16)
        self.verticalLayout_17.addLayout(self.horizontalLayout_12)
        self.radioButtonFitCsensor = QtWidgets.QRadioButton(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitCsensor.setFont(font)
        self.radioButtonFitCsensor.setObjectName("radioButtonFitCsensor")
        self.verticalLayout_17.addWidget(self.radioButtonFitCsensor)
        self.horizontalLayout_13.addWidget(self.groupBox_14)
        spacerItem23 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem23)
        self.verticalLayout_42.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_20.addLayout(self.verticalLayout_42)
        spacerItem24 = QtWidgets.QSpacerItem(13, 580, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem24)
        self.gridLayout.addLayout(self.horizontalLayout_20, 0, 0, 1, 1)
        MainAnalysisCoupledAntennasWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainAnalysisCoupledAntennasWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1158, 22))
        self.menubar.setObjectName("menubar")
        MainAnalysisCoupledAntennasWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainAnalysisCoupledAntennasWindow)
        self.statusbar.setObjectName("statusbar")
        MainAnalysisCoupledAntennasWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainAnalysisCoupledAntennasWindow)
        QtCore.QMetaObject.connectSlotsByName(MainAnalysisCoupledAntennasWindow)

    def retranslateUi(self, MainAnalysisCoupledAntennasWindow):
        _translate = QtCore.QCoreApplication.translate
        MainAnalysisCoupledAntennasWindow.setWindowTitle(_translate("MainAnalysisCoupledAntennasWindow", "Analysis Coupled Antennas"))
        self.pushButtonPreviousFile.setText(_translate("MainAnalysisCoupledAntennasWindow", "<"))
        self.pushButtonNextFile.setText(_translate("MainAnalysisCoupledAntennasWindow", ">"))
        self.groupBox_9.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "f min"))
        self.lineEditValueFmin.setText(_translate("MainAnalysisCoupledAntennasWindow", "0"))
        self.groupBox_8.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "f max"))
        self.lineEditValueFmax.setText(_translate("MainAnalysisCoupledAntennasWindow", "50"))
        self.label_3.setText(_translate("MainAnalysisCoupledAntennasWindow", "F2Min"))
        self.label.setText(_translate("MainAnalysisCoupledAntennasWindow", "F1Min"))
        self.label_4.setText(_translate("MainAnalysisCoupledAntennasWindow", "F2Max"))
        self.label_2.setText(_translate("MainAnalysisCoupledAntennasWindow", "F1Max"))
        self.radioButton2RegionsFit.setText(_translate("MainAnalysisCoupledAntennasWindow", "2 regions fit"))
        self.pushButtonFit.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "R0"))
        self.label_5.setText(_translate("MainAnalysisCoupledAntennasWindow", "Min"))
        self.lineEditMinR0.setText(_translate("MainAnalysisCoupledAntennasWindow", "0"))
        self.label_7.setText(_translate("MainAnalysisCoupledAntennasWindow", "Value"))
        self.lineEditValueR0.setText(_translate("MainAnalysisCoupledAntennasWindow", "0"))
        self.label_6.setText(_translate("MainAnalysisCoupledAntennasWindow", "Max"))
        self.lineEditMaxR0.setText(_translate("MainAnalysisCoupledAntennasWindow", "0.5"))
        self.radioButtonFitR0.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_2.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "R Antenna Reader (R1)"))
        self.label_33.setText(_translate("MainAnalysisCoupledAntennasWindow", "Min"))
        self.lineEditMinR1.setText(_translate("MainAnalysisCoupledAntennasWindow", "0"))
        self.label_34.setText(_translate("MainAnalysisCoupledAntennasWindow", "Value"))
        self.lineEditValueR1.setText(_translate("MainAnalysisCoupledAntennasWindow", "4.64"))
        self.label_32.setText(_translate("MainAnalysisCoupledAntennasWindow", "Max"))
        self.lineEditMaxR1.setText(_translate("MainAnalysisCoupledAntennasWindow", "10"))
        self.radioButtonFitR1.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_11.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "L Antenna Reader (L1)"))
        self.label_30.setText(_translate("MainAnalysisCoupledAntennasWindow", "Min"))
        self.lineEditMinL1.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-7"))
        self.label_31.setText(_translate("MainAnalysisCoupledAntennasWindow", "Value"))
        self.lineEditValueL1.setText(_translate("MainAnalysisCoupledAntennasWindow", "2.03e-6"))
        self.label_29.setText(_translate("MainAnalysisCoupledAntennasWindow", "Max"))
        self.lineEditMaxL1.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-5"))
        self.radioButtonFitL1.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_12.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "C Antenna Reader (C1)"))
        self.label_27.setText(_translate("MainAnalysisCoupledAntennasWindow", "Min"))
        self.lineEditMinC1.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-12"))
        self.label_28.setText(_translate("MainAnalysisCoupledAntennasWindow", "Value"))
        self.lineEditValueC1.setText(_translate("MainAnalysisCoupledAntennasWindow", "9.12e-12"))
        self.label_26.setText(_translate("MainAnalysisCoupledAntennasWindow", "Max"))
        self.lineEditMaxC1.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-10"))
        self.radioButtonFitC1.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_13.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "k (coupling factor)"))
        self.label_21.setText(_translate("MainAnalysisCoupledAntennasWindow", "Min"))
        self.lineEditMink.setText(_translate("MainAnalysisCoupledAntennasWindow", "0"))
        self.label_22.setText(_translate("MainAnalysisCoupledAntennasWindow", "Value"))
        self.lineEditValuek.setText(_translate("MainAnalysisCoupledAntennasWindow", "0"))
        self.label_20.setText(_translate("MainAnalysisCoupledAntennasWindow", "Max"))
        self.lineEditMaxk.setText(_translate("MainAnalysisCoupledAntennasWindow", "1"))
        self.radioButtonFitk.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_15.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "R Antenna Transponder (R2)"))
        self.label_24.setText(_translate("MainAnalysisCoupledAntennasWindow", "Min"))
        self.lineEditMinR2.setText(_translate("MainAnalysisCoupledAntennasWindow", "0"))
        self.label_25.setText(_translate("MainAnalysisCoupledAntennasWindow", "Value"))
        self.lineEditValueR2.setText(_translate("MainAnalysisCoupledAntennasWindow", "4.59"))
        self.label_23.setText(_translate("MainAnalysisCoupledAntennasWindow", "Max"))
        self.lineEditMaxR2.setText(_translate("MainAnalysisCoupledAntennasWindow", "10"))
        self.radioButtonFitR2.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_3.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "L Antenna Transponder (L2)"))
        self.label_15.setText(_translate("MainAnalysisCoupledAntennasWindow", "Min"))
        self.lineEditMinL2.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-6"))
        self.label_16.setText(_translate("MainAnalysisCoupledAntennasWindow", "Value"))
        self.lineEditValueL2.setText(_translate("MainAnalysisCoupledAntennasWindow", "2.79e-6"))
        self.label_14.setText(_translate("MainAnalysisCoupledAntennasWindow", "Max"))
        self.lineEditMaxL2.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-5"))
        self.radioButtonFitL2.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_4.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "C Antenna Transponder (C2)"))
        self.label_18.setText(_translate("MainAnalysisCoupledAntennasWindow", "Min"))
        self.lineEditMinC2.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-12"))
        self.label_19.setText(_translate("MainAnalysisCoupledAntennasWindow", "Value"))
        self.lineEditValueC2.setText(_translate("MainAnalysisCoupledAntennasWindow", "2.52e-11"))
        self.label_17.setText(_translate("MainAnalysisCoupledAntennasWindow", "Max"))
        self.lineEditMaxC2.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-10"))
        self.radioButtonFitC2.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.R_sensor.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "R Sensor"))
        self.label_9.setText(_translate("MainAnalysisCoupledAntennasWindow", "Min"))
        self.lineEditMinRsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e9"))
        self.label_10.setText(_translate("MainAnalysisCoupledAntennasWindow", "Value"))
        self.lineEditValueRsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e10"))
        self.label_8.setText(_translate("MainAnalysisCoupledAntennasWindow", "Max"))
        self.lineEditMaxRsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e10"))
        self.radioButtonFitRsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_14.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "C Sensor"))
        self.label_12.setText(_translate("MainAnalysisCoupledAntennasWindow", "Min"))
        self.lineEditMinCsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-13"))
        self.label_13.setText(_translate("MainAnalysisCoupledAntennasWindow", "Value"))
        self.lineEditValueCsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-13"))
        self.label_11.setText(_translate("MainAnalysisCoupledAntennasWindow", "Max"))
        self.lineEditMaxCsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "2e-12"))
        self.radioButtonFitCsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))

from .mplwidget4p import MplWidget4p
