# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'coupledAntennasAnalysisWindow_v0.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainAnalysisCoupledAntennasWindow(object):
    def setupUi(self, MainAnalysisCoupledAntennasWindow):
        MainAnalysisCoupledAntennasWindow.setObjectName("MainAnalysisCoupledAntennasWindow")
        MainAnalysisCoupledAntennasWindow.resize(1155, 674)
        self.centralwidget = QtWidgets.QWidget(MainAnalysisCoupledAntennasWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(13, 580, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.MplWidget4 = MplWidget4p(self.centralwidget)
        self.MplWidget4.setMinimumSize(QtCore.QSize(550, 400))
        self.MplWidget4.setObjectName("MplWidget4")
        self.verticalLayout_2.addWidget(self.MplWidget4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_9 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_9.setMinimumSize(QtCore.QSize(100, 70))
        self.groupBox_9.setObjectName("groupBox_9")
        self.lineEditValueFmin = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEditValueFmin.setGeometry(QtCore.QRect(20, 30, 50, 25))
        self.lineEditValueFmin.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueFmin.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueFmin.setFont(font)
        self.lineEditValueFmin.setObjectName("lineEditValueFmin")
        self.horizontalLayout.addWidget(self.groupBox_9)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setMinimumSize(QtCore.QSize(100, 70))
        self.groupBox_8.setObjectName("groupBox_8")
        self.lineEditValueFmax = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEditValueFmax.setGeometry(QtCore.QRect(20, 30, 50, 25))
        self.lineEditValueFmax.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueFmax.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueFmax.setFont(font)
        self.lineEditValueFmax.setObjectName("lineEditValueFmax")
        self.horizontalLayout.addWidget(self.groupBox_8)
        self.horizontalLayout_8.addLayout(self.horizontalLayout)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.pushButtonFit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonFit.setObjectName("pushButtonFit")
        self.horizontalLayout_8.addWidget(self.pushButtonFit)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        spacerItem7 = QtWidgets.QSpacerItem(13, 580, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMinimumSize(QtCore.QSize(220, 100))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 202, 98))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditMinR0 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditMinR0.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinR0.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinR0.setFont(font)
        self.lineEditMinR0.setObjectName("lineEditMinR0")
        self.horizontalLayout_2.addWidget(self.lineEditMinR0)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalSliderR0 = QtWidgets.QSlider(self.layoutWidget)
        self.horizontalSliderR0.setMinimum(0)
        self.horizontalSliderR0.setMaximum(10000)
        self.horizontalSliderR0.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderR0.setObjectName("horizontalSliderR0")
        self.gridLayout.addWidget(self.horizontalSliderR0, 0, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 1, 0, 1, 1)
        self.lineEditValueR0 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditValueR0.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueR0.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueR0.setFont(font)
        self.lineEditValueR0.setObjectName("lineEditValueR0")
        self.gridLayout.addWidget(self.lineEditValueR0, 2, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.lineEditMaxR0 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditMaxR0.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxR0.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxR0.setFont(font)
        self.lineEditMaxR0.setObjectName("lineEditMaxR0")
        self.horizontalLayout_2.addWidget(self.lineEditMaxR0)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.radioButtonFitR0 = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitR0.setFont(font)
        self.radioButtonFitR0.setObjectName("radioButtonFitR0")
        self.verticalLayout_3.addWidget(self.radioButtonFitR0)
        self.horizontalLayout_4.addWidget(self.groupBox)
        spacerItem10 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem10)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(220, 100))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 202, 98))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEditMinR1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditMinR1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinR1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinR1.setFont(font)
        self.lineEditMinR1.setObjectName("lineEditMinR1")
        self.horizontalLayout_3.addWidget(self.lineEditMinR1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalSliderR1 = QtWidgets.QSlider(self.layoutWidget1)
        self.horizontalSliderR1.setMinimum(0)
        self.horizontalSliderR1.setMaximum(10000)
        self.horizontalSliderR1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderR1.setObjectName("horizontalSliderR1")
        self.gridLayout_2.addWidget(self.horizontalSliderR1, 0, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem11, 1, 0, 1, 1)
        self.lineEditValueR1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditValueR1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueR1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueR1.setFont(font)
        self.lineEditValueR1.setObjectName("lineEditValueR1")
        self.gridLayout_2.addWidget(self.lineEditValueR1, 2, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.lineEditMaxR1 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEditMaxR1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxR1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxR1.setFont(font)
        self.lineEditMaxR1.setObjectName("lineEditMaxR1")
        self.horizontalLayout_3.addWidget(self.lineEditMaxR1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.radioButtonFitR1 = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitR1.setFont(font)
        self.radioButtonFitR1.setObjectName("radioButtonFitR1")
        self.verticalLayout_4.addWidget(self.radioButtonFitR1)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        spacerItem12 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem13 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem13)
        self.groupBox_11 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_11.setMinimumSize(QtCore.QSize(220, 100))
        self.groupBox_11.setObjectName("groupBox_11")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_11)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 202, 98))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.lineEditMinL1 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditMinL1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinL1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinL1.setFont(font)
        self.lineEditMinL1.setObjectName("lineEditMinL1")
        self.horizontalLayout_15.addWidget(self.lineEditMinL1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalSliderL1 = QtWidgets.QSlider(self.layoutWidget2)
        self.horizontalSliderL1.setMinimum(0)
        self.horizontalSliderL1.setMaximum(10000)
        self.horizontalSliderL1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderL1.setObjectName("horizontalSliderL1")
        self.gridLayout_9.addWidget(self.horizontalSliderL1, 0, 0, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem14, 1, 0, 1, 1)
        self.lineEditValueL1 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditValueL1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueL1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueL1.setFont(font)
        self.lineEditValueL1.setObjectName("lineEditValueL1")
        self.gridLayout_9.addWidget(self.lineEditValueL1, 2, 0, 1, 1)
        self.horizontalLayout_15.addLayout(self.gridLayout_9)
        self.lineEditMaxL1 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditMaxL1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxL1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxL1.setFont(font)
        self.lineEditMaxL1.setObjectName("lineEditMaxL1")
        self.horizontalLayout_15.addWidget(self.lineEditMaxL1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        self.radioButtonFitL1 = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitL1.setFont(font)
        self.radioButtonFitL1.setObjectName("radioButtonFitL1")
        self.verticalLayout_5.addWidget(self.radioButtonFitL1)
        self.horizontalLayout_14.addWidget(self.groupBox_11)
        spacerItem15 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem15)
        self.groupBox_12 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_12.setMinimumSize(QtCore.QSize(220, 100))
        self.groupBox_12.setObjectName("groupBox_12")
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_12)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 202, 98))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.lineEditMinC1 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEditMinC1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinC1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinC1.setFont(font)
        self.lineEditMinC1.setObjectName("lineEditMinC1")
        self.horizontalLayout_16.addWidget(self.lineEditMinC1)
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalSliderC1 = QtWidgets.QSlider(self.layoutWidget3)
        self.horizontalSliderC1.setMinimum(0)
        self.horizontalSliderC1.setMaximum(10000)
        self.horizontalSliderC1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderC1.setObjectName("horizontalSliderC1")
        self.gridLayout_10.addWidget(self.horizontalSliderC1, 0, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem16, 1, 0, 1, 1)
        self.lineEditValueC1 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEditValueC1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueC1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueC1.setFont(font)
        self.lineEditValueC1.setObjectName("lineEditValueC1")
        self.gridLayout_10.addWidget(self.lineEditValueC1, 2, 0, 1, 1)
        self.horizontalLayout_16.addLayout(self.gridLayout_10)
        self.lineEditMaxC1 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEditMaxC1.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxC1.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxC1.setFont(font)
        self.lineEditMaxC1.setObjectName("lineEditMaxC1")
        self.horizontalLayout_16.addWidget(self.lineEditMaxC1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.radioButtonFitC1 = QtWidgets.QRadioButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitC1.setFont(font)
        self.radioButtonFitC1.setObjectName("radioButtonFitC1")
        self.verticalLayout_6.addWidget(self.radioButtonFitC1)
        self.horizontalLayout_14.addWidget(self.groupBox_12)
        spacerItem17 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem17)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        spacerItem18 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem18)
        self.groupBox_13 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_13.setMinimumSize(QtCore.QSize(220, 100))
        self.groupBox_13.setObjectName("groupBox_13")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_13)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 20, 202, 98))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.lineEditMink = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEditMink.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMink.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMink.setFont(font)
        self.lineEditMink.setObjectName("lineEditMink")
        self.horizontalLayout_22.addWidget(self.lineEditMink)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.horizontalSliderk = QtWidgets.QSlider(self.layoutWidget4)
        self.horizontalSliderk.setMinimum(0)
        self.horizontalSliderk.setMaximum(10000)
        self.horizontalSliderk.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderk.setObjectName("horizontalSliderk")
        self.gridLayout_13.addWidget(self.horizontalSliderk, 0, 0, 1, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem19, 1, 0, 1, 1)
        self.lineEditValuek = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEditValuek.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValuek.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValuek.setFont(font)
        self.lineEditValuek.setObjectName("lineEditValuek")
        self.gridLayout_13.addWidget(self.lineEditValuek, 2, 0, 1, 1)
        self.horizontalLayout_22.addLayout(self.gridLayout_13)
        self.lineEditMaxk = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEditMaxk.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxk.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxk.setFont(font)
        self.lineEditMaxk.setObjectName("lineEditMaxk")
        self.horizontalLayout_22.addWidget(self.lineEditMaxk)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.radioButtonFitk = QtWidgets.QRadioButton(self.layoutWidget4)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitk.setFont(font)
        self.radioButtonFitk.setChecked(True)
        self.radioButtonFitk.setObjectName("radioButtonFitk")
        self.verticalLayout_7.addWidget(self.radioButtonFitk)
        self.horizontalLayout_21.addWidget(self.groupBox_13)
        spacerItem20 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem20)
        self.groupBox_15 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_15.setMinimumSize(QtCore.QSize(220, 100))
        self.groupBox_15.setObjectName("groupBox_15")
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_15)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 20, 202, 98))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.lineEditMinR2 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEditMinR2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinR2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinR2.setFont(font)
        self.lineEditMinR2.setObjectName("lineEditMinR2")
        self.horizontalLayout_23.addWidget(self.lineEditMinR2)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.horizontalSliderR2 = QtWidgets.QSlider(self.layoutWidget5)
        self.horizontalSliderR2.setMinimum(0)
        self.horizontalSliderR2.setMaximum(10000)
        self.horizontalSliderR2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderR2.setObjectName("horizontalSliderR2")
        self.gridLayout_14.addWidget(self.horizontalSliderR2, 0, 0, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem21, 1, 0, 1, 1)
        self.lineEditValueR2 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEditValueR2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueR2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueR2.setFont(font)
        self.lineEditValueR2.setObjectName("lineEditValueR2")
        self.gridLayout_14.addWidget(self.lineEditValueR2, 2, 0, 1, 1)
        self.horizontalLayout_23.addLayout(self.gridLayout_14)
        self.lineEditMaxR2 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEditMaxR2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxR2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxR2.setFont(font)
        self.lineEditMaxR2.setObjectName("lineEditMaxR2")
        self.horizontalLayout_23.addWidget(self.lineEditMaxR2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.radioButtonFitR2 = QtWidgets.QRadioButton(self.layoutWidget5)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitR2.setFont(font)
        self.radioButtonFitR2.setObjectName("radioButtonFitR2")
        self.verticalLayout_8.addWidget(self.radioButtonFitR2)
        self.horizontalLayout_21.addWidget(self.groupBox_15)
        spacerItem22 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem22)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem23 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem23)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMinimumSize(QtCore.QSize(220, 100))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 20, 202, 98))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.layoutWidget6)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEditMinL2 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEditMinL2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinL2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinL2.setFont(font)
        self.lineEditMinL2.setObjectName("lineEditMinL2")
        self.horizontalLayout_6.addWidget(self.lineEditMinL2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalSliderL2 = QtWidgets.QSlider(self.layoutWidget6)
        self.horizontalSliderL2.setMinimum(0)
        self.horizontalSliderL2.setMaximum(10000)
        self.horizontalSliderL2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderL2.setObjectName("horizontalSliderL2")
        self.gridLayout_3.addWidget(self.horizontalSliderL2, 0, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem24, 1, 0, 1, 1)
        self.lineEditValueL2 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEditValueL2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueL2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueL2.setFont(font)
        self.lineEditValueL2.setObjectName("lineEditValueL2")
        self.gridLayout_3.addWidget(self.lineEditValueL2, 2, 0, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_3)
        self.lineEditMaxL2 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEditMaxL2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxL2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxL2.setFont(font)
        self.lineEditMaxL2.setObjectName("lineEditMaxL2")
        self.horizontalLayout_6.addWidget(self.lineEditMaxL2)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.radioButtonFitL2 = QtWidgets.QRadioButton(self.layoutWidget6)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitL2.setFont(font)
        self.radioButtonFitL2.setObjectName("radioButtonFitL2")
        self.verticalLayout_9.addWidget(self.radioButtonFitL2)
        self.horizontalLayout_5.addWidget(self.groupBox_3)
        spacerItem25 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem25)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(220, 100))
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 20, 202, 98))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.layoutWidget7)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEditMinC2 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEditMinC2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinC2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinC2.setFont(font)
        self.lineEditMinC2.setObjectName("lineEditMinC2")
        self.horizontalLayout_7.addWidget(self.lineEditMinC2)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalSliderC2 = QtWidgets.QSlider(self.layoutWidget7)
        self.horizontalSliderC2.setMinimum(0)
        self.horizontalSliderC2.setMaximum(10000)
        self.horizontalSliderC2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderC2.setObjectName("horizontalSliderC2")
        self.gridLayout_4.addWidget(self.horizontalSliderC2, 0, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem26, 1, 0, 1, 1)
        self.lineEditValueC2 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEditValueC2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueC2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueC2.setFont(font)
        self.lineEditValueC2.setObjectName("lineEditValueC2")
        self.gridLayout_4.addWidget(self.lineEditValueC2, 2, 0, 1, 1)
        self.horizontalLayout_7.addLayout(self.gridLayout_4)
        self.lineEditMaxC2 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEditMaxC2.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxC2.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxC2.setFont(font)
        self.lineEditMaxC2.setObjectName("lineEditMaxC2")
        self.horizontalLayout_7.addWidget(self.lineEditMaxC2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.radioButtonFitC2 = QtWidgets.QRadioButton(self.layoutWidget7)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitC2.setFont(font)
        self.radioButtonFitC2.setObjectName("radioButtonFitC2")
        self.verticalLayout_10.addWidget(self.radioButtonFitC2)
        self.horizontalLayout_5.addWidget(self.groupBox_4)
        spacerItem27 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem27)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        spacerItem28 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem28)
        self.R_sensor = QtWidgets.QGroupBox(self.centralwidget)
        self.R_sensor.setMinimumSize(QtCore.QSize(220, 100))
        self.R_sensor.setObjectName("R_sensor")
        self.layoutWidget8 = QtWidgets.QWidget(self.R_sensor)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 20, 202, 98))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.layoutWidget8)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.lineEditMinRsensor = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEditMinRsensor.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinRsensor.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinRsensor.setFont(font)
        self.lineEditMinRsensor.setObjectName("lineEditMinRsensor")
        self.horizontalLayout_18.addWidget(self.lineEditMinRsensor)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalSliderRsensor = QtWidgets.QSlider(self.layoutWidget8)
        self.horizontalSliderRsensor.setMinimum(0)
        self.horizontalSliderRsensor.setMaximum(10000)
        self.horizontalSliderRsensor.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderRsensor.setObjectName("horizontalSliderRsensor")
        self.gridLayout_11.addWidget(self.horizontalSliderRsensor, 0, 0, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem29, 1, 0, 1, 1)
        self.lineEditValueRsensor = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEditValueRsensor.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueRsensor.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueRsensor.setFont(font)
        self.lineEditValueRsensor.setObjectName("lineEditValueRsensor")
        self.gridLayout_11.addWidget(self.lineEditValueRsensor, 2, 0, 1, 1)
        self.horizontalLayout_18.addLayout(self.gridLayout_11)
        self.lineEditMaxRsensor = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEditMaxRsensor.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxRsensor.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxRsensor.setFont(font)
        self.lineEditMaxRsensor.setObjectName("lineEditMaxRsensor")
        self.horizontalLayout_18.addWidget(self.lineEditMaxRsensor)
        self.verticalLayout_11.addLayout(self.horizontalLayout_18)
        self.radioButtonFitRsensor = QtWidgets.QRadioButton(self.layoutWidget8)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitRsensor.setFont(font)
        self.radioButtonFitRsensor.setObjectName("radioButtonFitRsensor")
        self.verticalLayout_11.addWidget(self.radioButtonFitRsensor)
        self.horizontalLayout_17.addWidget(self.R_sensor)
        spacerItem30 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem30)
        self.groupBox_14 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_14.setMinimumSize(QtCore.QSize(220, 100))
        self.groupBox_14.setObjectName("groupBox_14")
        self.layoutWidget9 = QtWidgets.QWidget(self.groupBox_14)
        self.layoutWidget9.setGeometry(QtCore.QRect(10, 20, 202, 98))
        self.layoutWidget9.setObjectName("layoutWidget9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.layoutWidget9)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.lineEditMinCsensor = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEditMinCsensor.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMinCsensor.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMinCsensor.setFont(font)
        self.lineEditMinCsensor.setObjectName("lineEditMinCsensor")
        self.horizontalLayout_19.addWidget(self.lineEditMinCsensor)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.horizontalSliderCsensor = QtWidgets.QSlider(self.layoutWidget9)
        self.horizontalSliderCsensor.setMinimum(0)
        self.horizontalSliderCsensor.setMaximum(10000)
        self.horizontalSliderCsensor.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderCsensor.setObjectName("horizontalSliderCsensor")
        self.gridLayout_12.addWidget(self.horizontalSliderCsensor, 0, 0, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_12.addItem(spacerItem31, 1, 0, 1, 1)
        self.lineEditValueCsensor = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEditValueCsensor.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditValueCsensor.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditValueCsensor.setFont(font)
        self.lineEditValueCsensor.setObjectName("lineEditValueCsensor")
        self.gridLayout_12.addWidget(self.lineEditValueCsensor, 2, 0, 1, 1)
        self.horizontalLayout_19.addLayout(self.gridLayout_12)
        self.lineEditMaxCsensor = QtWidgets.QLineEdit(self.layoutWidget9)
        self.lineEditMaxCsensor.setMinimumSize(QtCore.QSize(50, 25))
        self.lineEditMaxCsensor.setMaximumSize(QtCore.QSize(50, 25))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.lineEditMaxCsensor.setFont(font)
        self.lineEditMaxCsensor.setObjectName("lineEditMaxCsensor")
        self.horizontalLayout_19.addWidget(self.lineEditMaxCsensor)
        self.verticalLayout_12.addLayout(self.horizontalLayout_19)
        self.radioButtonFitCsensor = QtWidgets.QRadioButton(self.layoutWidget9)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.radioButtonFitCsensor.setFont(font)
        self.radioButtonFitCsensor.setObjectName("radioButtonFitCsensor")
        self.verticalLayout_12.addWidget(self.radioButtonFitCsensor)
        self.horizontalLayout_17.addWidget(self.groupBox_14)
        spacerItem32 = QtWidgets.QSpacerItem(17, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem32)
        self.verticalLayout.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        spacerItem33 = QtWidgets.QSpacerItem(13, 580, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem33)
        self.gridLayout_5.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        MainAnalysisCoupledAntennasWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainAnalysisCoupledAntennasWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1155, 22))
        self.menubar.setObjectName("menubar")
        MainAnalysisCoupledAntennasWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainAnalysisCoupledAntennasWindow)
        self.statusbar.setObjectName("statusbar")
        MainAnalysisCoupledAntennasWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainAnalysisCoupledAntennasWindow)
        QtCore.QMetaObject.connectSlotsByName(MainAnalysisCoupledAntennasWindow)

    def retranslateUi(self, MainAnalysisCoupledAntennasWindow):
        _translate = QtCore.QCoreApplication.translate
        MainAnalysisCoupledAntennasWindow.setWindowTitle(_translate("MainAnalysisCoupledAntennasWindow", "Analysis Coupled Antennas"))
        self.groupBox_9.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "f min"))
        self.lineEditValueFmin.setText(_translate("MainAnalysisCoupledAntennasWindow", "0"))
        self.groupBox_8.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "f max"))
        self.lineEditValueFmax.setText(_translate("MainAnalysisCoupledAntennasWindow", "50"))
        self.pushButtonFit.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "R0"))
        self.lineEditMinR0.setText(_translate("MainAnalysisCoupledAntennasWindow", "0"))
        self.lineEditValueR0.setText(_translate("MainAnalysisCoupledAntennasWindow", "0"))
        self.lineEditMaxR0.setText(_translate("MainAnalysisCoupledAntennasWindow", "0.5"))
        self.radioButtonFitR0.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_2.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "R Antenna Reader (R1)"))
        self.lineEditMinR1.setText(_translate("MainAnalysisCoupledAntennasWindow", "0"))
        self.lineEditValueR1.setText(_translate("MainAnalysisCoupledAntennasWindow", "4.64"))
        self.lineEditMaxR1.setText(_translate("MainAnalysisCoupledAntennasWindow", "10"))
        self.radioButtonFitR1.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_11.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "L Antenna Reader (L1)"))
        self.lineEditMinL1.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-7"))
        self.lineEditValueL1.setText(_translate("MainAnalysisCoupledAntennasWindow", "2.03e-6"))
        self.lineEditMaxL1.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-5"))
        self.radioButtonFitL1.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_12.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "C Antenna Reader (C1)"))
        self.lineEditMinC1.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-12"))
        self.lineEditValueC1.setText(_translate("MainAnalysisCoupledAntennasWindow", "9.12e-12"))
        self.lineEditMaxC1.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-10"))
        self.radioButtonFitC1.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_13.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "k (coupling factor)"))
        self.lineEditMink.setText(_translate("MainAnalysisCoupledAntennasWindow", "0"))
        self.lineEditValuek.setText(_translate("MainAnalysisCoupledAntennasWindow", "0"))
        self.lineEditMaxk.setText(_translate("MainAnalysisCoupledAntennasWindow", "1"))
        self.radioButtonFitk.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_15.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "R Antenna Transponder (R2)"))
        self.lineEditMinR2.setText(_translate("MainAnalysisCoupledAntennasWindow", "0"))
        self.lineEditValueR2.setText(_translate("MainAnalysisCoupledAntennasWindow", "4.59"))
        self.lineEditMaxR2.setText(_translate("MainAnalysisCoupledAntennasWindow", "10"))
        self.radioButtonFitR2.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_3.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "L Antenna Transponder (L2)"))
        self.lineEditMinL2.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-6"))
        self.lineEditValueL2.setText(_translate("MainAnalysisCoupledAntennasWindow", "2.79e-6"))
        self.lineEditMaxL2.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-5"))
        self.radioButtonFitL2.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_4.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "C Antenna Transponder (C2)"))
        self.lineEditMinC2.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-12"))
        self.lineEditValueC2.setText(_translate("MainAnalysisCoupledAntennasWindow", "2.52e-11"))
        self.lineEditMaxC2.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-10"))
        self.radioButtonFitC2.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.R_sensor.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "R Sensor"))
        self.lineEditMinRsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e9"))
        self.lineEditValueRsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e10"))
        self.lineEditMaxRsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e10"))
        self.radioButtonFitRsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))
        self.groupBox_14.setTitle(_translate("MainAnalysisCoupledAntennasWindow", "C Sensor"))
        self.lineEditMinCsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-13"))
        self.lineEditValueCsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "1e-13"))
        self.lineEditMaxCsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "2e-12"))
        self.radioButtonFitCsensor.setText(_translate("MainAnalysisCoupledAntennasWindow", "Fit"))

from .mplwidget4p import MplWidget4p
